
-- Добавление нового посетителя
INSERT INTO visitors (first_name, last_name, phone, email, loyalty_card)
VALUES ('Игорь', 'Волков', '+7-999-678-90-12', 'igor@mail.ru', 'LC-004');
COMMIT;

--Добавление нового блюда
INSERT INTO dishes (category_id, name, description, price, weight_grams, calories, preparation_time_minutes)
VALUES (4, 'Свиные ребрышки BBQ', 'Свиные ребрышки в барбекю соусе', 890.00, 350, 750, 30);
COMMIT;

--Добавление ингредиента и связь с блюдом
-- Сначала добавим новый ингредиент
INSERT INTO ingredients (name, unit, stock_quantity)
VALUES ('Соус BBQ', 'л', 5.0);

-- Затем свяжем с блюдом (предположим, id нового блюда = 17)
INSERT INTO dish_ingredients (dish_id, ingredient_id, quantity_required)
VALUES (17, (SELECT id FROM ingredients WHERE name = 'Соус BBQ'), 0.1);
COMMIT;


--Добавление заказа с позициями
-- Создаем заказ
INSERT INTO orders (visitor_id, waiter_id, table_number, order_time, status, total_amount)
VALUES (2, 3, 8, CURRENT_TIMESTAMP, 'new', 0);

-- Добавляем позиции (предположим, id нового заказа = 5)
INSERT INTO order_items (order_id, dish_id, quantity, price_at_moment, special_requests)
VALUES (5, 3, 1, 480.00, NULL);

INSERT INTO order_items (order_id, dish_id, quantity, price_at_moment, special_requests)
VALUES (5, 14, 2, 250.00, 'Без льда');

-- Обновляем общую сумму заказа
UPDATE orders SET total_amount = (
    SELECT SUM(quantity * price_at_moment)
    FROM order_items
    WHERE order_id = 5
)
WHERE id = 5;
COMMIT;


--Массовая вставка 
INSERT ALL
    INTO ingredients (name, unit, stock_quantity) VALUES ('Кинза', 'кг', 2.0)
    INTO ingredients (name, unit, stock_quantity) VALUES ('Петрушка', 'кг', 3.5)
    INTO ingredients (name, unit, stock_quantity) VALUES ('Укроп', 'кг', 3.0)
SELECT * FROM dual;
COMMIT;

--UPDATE

-- Увеличение цены на 10%
UPDATE dishes
SET price = price * 1.1  -- повышаем цену на 10%
WHERE category_id = 4;   -- только основные блюда
COMMIT;

--Обновление статуса заказа
UPDATE orders
SET status = 'served'
WHERE id = 4 AND status = 'new';
COMMIT;

--Изменение количества ингридиентов на складе
UPDATE ingredients
SET stock_quantity = stock_quantity - 0.5
WHERE name = 'Куриное филе';
COMMIT;

--Обновление статуса бронирования
UPDATE reservations
SET status = 'completed'
WHERE reservation_time < SYSDATE AND status = 'confirmed';
COMMIT;

--Обновление с подзапросом
-- Повысить зарплату официантам, которые обслужили больше 2 заказов
UPDATE waiters
SET hourly_rate = hourly_rate * 1.15
WHERE id IN (
    SELECT waiter_id
    FROM orders
    GROUP BY waiter_id
    HAVING COUNT(*) > 2
);
COMMIT;

--Обновление с CASE
UPDATE orders
SET status = CASE
    WHEN total_amount > 3000 THEN 'vip'
    WHEN status = 'paid' THEN 'completed'
    ELSE status
END
WHERE order_time > SYSDATE - 7;
COMMIT;

--Delete
--Удаление отмененных бронирований старше 30 дней
DELETE FROM reservations
WHERE status = 'cancelled'
AND reservation_time < SYSDATE - 30;
COMMIT;

--Удаление посетителя без заказов
DELETE FROM visitors
WHERE id NOT IN (SELECT DISTINCT visitor_id FROM orders WHERE visitor_id IS NOT NULL)
AND registered_at < SYSDATE - 365;
COMMIT;



--Триггеры

--Триггер: автоматическое обновление total_amount в orders
CREATE OR REPLACE TRIGGER trg_update_order_total
AFTER INSERT OR UPDATE OR DELETE ON order_items
FOR EACH ROW
DECLARE
    v_order_id orders.id%TYPE;
BEGIN
    -- Определяем ID заказа
    IF INSERTING THEN
        v_order_id := :NEW.order_id;
    ELSIF UPDATING THEN
        v_order_id := :NEW.order_id;
    ELSE
        v_order_id := :OLD.order_id;
    END IF;
    -- Обновляем общую сумму заказа
    UPDATE orders
    SET total_amount = (
        SELECT NVL(SUM(quantity * price_at_moment), 0)
        FROM order_items
        WHERE order_id = v_order_id
    )
    WHERE id = v_order_id;
END;


--Триггер: автоматическое проставление даты регистрации
CREATE OR REPLACE TRIGGER trg_visitors_registered
BEFORE INSERT ON visitors
FOR EACH ROW
BEGIN
    :NEW.registered_at := CURRENT_TIMESTAMP;
END;

--Триггер логирование изменения цен
-- Сначала создадим таблицу для логов
CREATE TABLE price_change_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_id INTEGER,
    old_price NUMBER(10,2),
    new_price NUMBER(10,2),
    changed_by VARCHAR2(100),
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Сначала создадим таблицу для логов
CREATE TABLE price_change_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dish_id INTEGER,
    old_price NUMBER(10,2),
    new_price NUMBER(10,2),
    changed_by VARCHAR2(100),
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Триггер на изменение цены
CREATE OR REPLACE TRIGGER trg_log_price_changes
AFTER UPDATE OF price ON dishes
FOR EACH ROW
BEGIN
    IF :OLD.price != :NEW.price THEN
        INSERT INTO price_change_log (dish_id, old_price, new_price, changed_by)
        VALUES (:OLD.id, :OLD.price, :NEW.price, USER);
    END IF;
END;
/
