BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE order_items CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE reservations CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE dish_ingredients CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE dishes CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE categories CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ingredients CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE waiters CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE visitors CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

CREATE TABLE visitors (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    phone VARCHAR2(20) UNIQUE,
    email VARCHAR2(100) UNIQUE,
    loyalty_card VARCHAR2(20) UNIQUE,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_visitors_email CHECK (REGEXP_LIKE(email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'))
);

CREATE TABLE reservations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_id INTEGER NOT NULL REFERENCES visitors(id) ON DELETE CASCADE,
    table_number INTEGER NOT NULL,
    reservation_time TIMESTAMP NOT NULL,
    guests_count INTEGER NOT NULL CHECK (guests_count > 0 AND guests_count <= 20),
    status VARCHAR2(20) DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'cancelled', 'completed')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_table_reservation UNIQUE (table_number, reservation_time)
);

CREATE TABLE categories (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE,
    description VARCHAR2(1000),
    display_order INTEGER DEFAULT 0
);

CREATE TABLE dishes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    name VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(1000),
    price NUMBER(10,2) NOT NULL CHECK (price > 0),
    weight_grams INTEGER CHECK (weight_grams > 0),
    calories INTEGER CHECK (calories >= 0),
    is_available NUMBER(1) DEFAULT 1 CHECK (is_available IN (0,1)),
    preparation_time_minutes INTEGER CHECK (preparation_time_minutes > 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ingredients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE,
    unit VARCHAR2(20) NOT NULL CHECK (unit IN ('кг', 'г', 'л', 'мл', 'шт')),
    stock_quantity NUMBER(10,2) DEFAULT 0 CHECK (stock_quantity >= 0)
);

CREATE TABLE dish_ingredients (
    dish_id INTEGER NOT NULL REFERENCES dishes(id) ON DELETE CASCADE,
    ingredient_id INTEGER NOT NULL REFERENCES ingredients(id) ON DELETE CASCADE,
    quantity_required NUMBER(10,2) NOT NULL CHECK (quantity_required > 0),
    PRIMARY KEY (dish_id, ingredient_id)
);

CREATE TABLE waiters (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    hire_date DATE NOT NULL,
    hourly_rate NUMBER(10,2) NOT NULL CHECK (hourly_rate >= 0),
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0,1))
);

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_id INTEGER REFERENCES visitors(id) ON DELETE SET NULL,
    waiter_id INTEGER NOT NULL REFERENCES waiters(id) ON DELETE CASCADE,
    table_number INTEGER NOT NULL,
    order_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'new' CHECK (status IN ('new', 'preparing', 'served', 'paid', 'cancelled')),
    total_amount NUMBER(10,2) DEFAULT 0 CHECK (total_amount >= 0)
);

CREATE TABLE order_items (
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    dish_id INTEGER NOT NULL REFERENCES dishes(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    price_at_moment NUMBER(10,2) NOT NULL CHECK (price_at_moment > 0),
    special_requests VARCHAR2(1000),
    PRIMARY KEY (order_id, dish_id)
);

CREATE INDEX idx_visitors_phone ON visitors(phone);
CREATE INDEX idx_visitors_email ON visitors(email);
CREATE INDEX idx_reservations_time ON reservations(reservation_time);
CREATE INDEX idx_reservations_visitor ON reservations(visitor_id);
CREATE INDEX idx_dishes_category ON dishes(category_id);
CREATE INDEX idx_dishes_price ON dishes(price);
CREATE INDEX idx_dishes_available ON dishes(is_available);
CREATE INDEX idx_orders_time ON orders(order_time);
CREATE INDEX idx_orders_visitor ON orders(visitor_id);
CREATE INDEX idx_orders_waiter ON orders(waiter_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orderitems_order ON order_items(order_id);